name: ${pom.artifactId}
version: ${pom.version}
description: Keeps track of players' playtime.

main: net.omniscimus.bukkit.proposalvoting.Main
database: false

commands:
   democracy:
      aliases: [dc]
      description: The main command for the ${pom.parent.artifactId} plugin.
      permission: proposalvoting.user
permissions:
   democracy.user:
      default: true
   democracy.admin:
      default: op
